routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', PostController::class);

app/Models/Category/Category.php
<?php

namespace App\Models\Category;

use App\Models\Post\Post;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Category extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'title','slug','content',
    ];

    /**
     * The posts that belong to the category.
     */
    public function posts(): BelongsToMany
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Models/Post/Post.php
<?php

namespace App\Models\Post;

use DateTime;
use Carbon\Carbon;
use App\Models\Category\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'title','slug','content','status','published_at'
    ];

    /**
     * The attributes that should be cast.
     * @var array
     */
    protected $casts = [
        'published_at'  => 'datetime',
    ];

    /**
     * The categories that belong to the post.
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests;
    use DispatchesJobs;
    use ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\Post\Post;
use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->has('q')) {
            $posts = Post::where('title', 'LIKE', '%'.$request->get('q').'%');
        } else {
            $posts = Post::query();
        }

        if( $request->has('order')) {
            $posts = $posts->orderBy($request->get('orderby'), $request->get('order'));
        } else {
            $posts = $posts->orderBy('created_at', 'DESC');
        }

        $posts = $posts->get();

        return view('posts/index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts/new');
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {

        $post = new Post();
        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->status = $request->status;
        $post->content = $request->content;
        $post->published_at = $request->status == 'draft' ? null : $request->published_at;
        $post->save();

        @session_start();
        $_SESSION['post_message'] = 'Post succesfully created';

        return redirect()->route('posts.edit', $post);
    }

    /**
     * Display the specified resource.
     * @param  \App\Models\Post\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        if ($post->status === 'draft') {
            abort(404);
        } elseif ($post->status === 'planned') {
            if (! $post->published_at) {
                abort(404);
            } elseif ($post->published_at > Carbon::now()) {
                abort(404);
            }
        }

        return view('posts.view', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param  \App\Models\Post\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts/edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {

        if ($post->published_at && $request->published_at->equalTo($post->published_at)) {
            // If the given publishDate is equal to the current stored published_at
            if ($request->status === 'planned' && $request->published_at < Carbon::now()) {
                // Update post to published if the published_at date has passed
                $status = 'published';
            }
        }

        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->status = $request->status;
        $post->content = $request->content;
        $post->published_at = $request->status == 'draft' ? null : $request->published_at;
        $post->save();

        @session_start();
        $_SESSION['post_message'] = 'Post succesfully updated';

        return redirect()->route('posts.edit', $post);
    }

    /**
     * Remove the specified resource from storage.
     * @param  \App\Models\Post\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (! $post->trashed()) {
            $post->delete();
        }

        @session_start();
        $_SESSION['post_message'] = 'Post "'.$post->title.'" has been deleted.';

        return redirect()->route('posts.index');
    }
}

resources/views/posts/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit blog post')

@section('content_header')
    <h1>Edit blog post "{{ $post->title }}"</h1>
@stop

@section('content')
    @foreach ($errors->all() as $message)
        <x-adminlte-callout theme="warning" title="Warning">
            {{ $message }}
        </x-adminlte-callout>
    @endforeach

    @if (@session_start() && isset($_SESSION['post_message']))
        <x-adminlte-callout theme="success" title="Success">
            {{ $_SESSION['post_message'] }}
            @php unset($_SESSION['post_message']) @endphp
        </x-adminlte-callout>
    @endif

    <form method="POST" action="{{ route('posts.update', $post) }}">
        @csrf
        @method('patch')

        <x-adminlte-input name="title" label="Title" placeholder="" top-class="col-md-6" :value="$post->title"/>

        <x-adminlte-input name="slug" label="Slug" placeholder="" top-class="col-md-6" :value="$post->slug"/>

        <x-adminlte-select name="status" label="Post status" top-class="col-md-6">
            <option value="draft" @if ($post->status === 'draft') selected @endif>
                Draft
            </option>
            <option value="published" @if ($post->status === 'published') selected @endif>
                Published
            </option>
            <option value="planned" @if ($post->status === 'planned') selected @endif>
                Planned
            </option>
        </x-adminlte-select>

        <x-adminlte-input name="published_at" label="Publication date" type="datetime-local" top-class="col-md-6" :value="$post->published_at ? $post->published_at->format('Y-m-d\TH:i:s') : '' "/>

        <x-adminlte-textarea name="content" label="Content" top-class="col-md-6" >
            {{ $post->content }}
        </x-adminlte-textarea>

        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save"/>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/posts/index.blade.php
@extends('adminlte::page')

@section('title', 'Blog posts')

@section('plugins.Datatables', true)

@section('content_header')
    <h1>Blog posts</h1>
@stop

@section('content')
    @if (@session_start() && isset($_SESSION['post_message']))
        <x-adminlte-callout theme="success" title="Success">
            {{ $_SESSION['post_message'] }}
            @php unset($_SESSION['post_message']) @endphp
        </x-adminlte-callout>
    @endif

    @php
    $headers = ['status', 'title', 'slug', 'published_at', 'actions'];
    $config = [
        'data' => $posts->map(function($item) {
            return [
                $item->status,
                $item->title,
                $item->slug,
                $item->published_at,
                '<a href="'.route('posts.edit', $item).'" class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit">
                    <i class="fa fa-lg fa-fw fa-pen"></i>
                </a>
                <a href="'.route('posts.show', $item).'" class="btn btn-xs btn-default text-teal mx-1 shadow" title="Details">
                   <i class="fa fa-lg fa-fw fa-eye"></i>
                </a>
                <form method="POST" action="'.route('posts.destroy', $item).'">
                    <input type="hidden" name="_token" value="'.csrf_token().'" />
                    <input type="hidden" name="_method" value="delete">

                    <button class="btn btn-xs btn-default text-red mx-1 shadow" title="Delete">
                       <i class="fas fa-lg fa-trash"></i>
                    </button>
                </form>'
            ];
        }),
    ];
    @endphp

    <x-adminlte-datatable id="published_posts" :heads="$headers" head-theme="dark" :config="$config" striped hoverable bordered compressed/>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/posts/new.blade.php
@extends('adminlte::page')

@section('title', 'New blog post')

@section('content_header')
    <h1>New blog post</h1>
@stop

@section('content')
    @foreach ($errors->all() as $message)
        <x-adminlte-callout theme="warning" title="Warning">
            {{ $message }}
        </x-adminlte-callout>
    @endforeach

    <form method="POST" action="{{ route('posts.store') }}">
        @csrf

        <x-adminlte-input name="title" label="Title" top-class="col-md-6" />

        <x-adminlte-input name="slug" label="Slug" top-class="col-md-6" />

        <x-adminlte-select name="status" label="Post status" top-class="col-md-6">
            <option value="draft">
                Draft
            </option>
            <option value="published">
                Published
            </option>
            <option value="planned">
                Planned
            </option>
        </x-adminlte-select>

        <x-adminlte-input name="published_at" label="Publication date" type="datetime-local" top-class="col-md-6"/>

        <x-adminlte-textarea name="content" label="Content" top-class="col-md-6"></x-adminlte-textarea>

        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save"/>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/posts/view.blade.php
@php dd($post) @endphp